spring.application.name=${APP_NAME}
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DB_NAME}

api.key.name=${API_KEY_HEADER}
api.key.value=${API_KEY}
frontend.url=${FRONTEND_URL}
