# spring.application.name=${APP_NAME}
# spring.data.mongodb.uri=${MONGODB_URI}
# spring.data.mongodb.database=${MONGODB_DB_NAME}

api.key.name=API-KEY
api.key.value=b499064d-c054-4cf6-adbb-dfcae626fed4
frontend.url=http://localhost:3000

spring.application.name=handler
spring.data.mongodb.uri=mongodb+srv://vyang2968:2183ppSTMUU8J3zl@survey.pyhro.mongodb.net/
spring.data.mongodb.database=responses
