name: Trigger auto deployment for planesurvey

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'handler/**'
    - '.github/workflows/planesurvey-AutoDeployTrigger-f9436bf6-4d15-4387-9392-e2c892c73dec.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PLANESURVEY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PLANESURVEY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PLANESURVEY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/handler 
          registryUrl: docker.io
          registryUsername: ${{ secrets.PLANESURVEY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PLANESURVEY_REGISTRY_PASSWORD }}
          containerAppName: planesurvey
          resourceGroup: general
          imageToBuild: vyang2968/planesurvey:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


